name: go-test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:16.9
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 2s
          --health-timeout 5s
          --health-retries 10

    env:
      MAPSERVER_TEST_POSTGRES_DSN: host=127.0.0.1 port=5432 user=postgres password=postgres dbname=postgres

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5.6.0
      with:
        go-version: '1.24'

    - name: test
      run: go test ./... -coverprofile=profile.cov

    - uses: shogo82148/actions-goveralls@v1.9.1
      with:
        path-to-profile: profile.cov
